stages:
  - build
  - deploy

variables:
  KUBECONFIG: /tmp/kubeconfig.yaml

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG app
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy:
  image: bitnami/kubectl:latest
  stage: deploy
  script:
    - echo "$KUBECONFIG_CONTENT" > $KUBECONFIG
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
